### ISSUE TITLE
Backport v2.0 to 1.16.1?

### ISSUE THREAD

**Issue by SnaveSutit** [ajknowles11/chains-link#2]
I know this is one of those requests that every mod author hates to hear/get. But I was wondering if we could get an official backport. If not I'll just create a custom build but it would be nicer to have an official backport. I'm building a simple modpack to play with my friends and we're playing on 1.16.1 because better nether hasn't updated yet.

I understand if you refuse, it's a lot of extra unneeded work to backport.

Thank you for your time,
Snave

**Comment by ajknowles11** [comment]
That's a completely understandable request, I'll work on it as soon as I get the chance.

**Comment by SnaveSutit** [comment]
Thanks! :)

**Comment by ajknowles11** [comment]
Okay, I just uploaded a version for 1.16.1. Let me know if there are any issues, some of my code is a little ugly so I can rewrite stuff if it causes compatibility problems.
