### ISSUE TITLE
Update to Minecraft 1.16.3?

### ISSUE THREAD

**Issue by copygirl** [ajknowles11/chains-link#3]
The mod currently has a hard dependency on 1.16.2 and thus doesn't run in 1.16.3, which is kind of unfortunate because it might actually work without any additional changes.

```
[12:03:27] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: chains requires {minecraft @ [1.16.2]}
```

**Comment by ajknowles11** [comment]
Whoops, that was a really simple fix too. Thanks for pointing that out, seems like it works fine in 1.16.3 now.

**Comment by copygirl** [comment]
Would you be able to upload this fix as a new release on CurseForge? The modpack tool I use isn't able to pick up additional files. (They're not exposed to the internal Twitch Launcher API or so.) Alternatively, I might still be able to include the mod's .jar directly, or maybe the direct download URL.

**Comment by ajknowles11** [comment]
I made a new release, let me know if there are any other issues but I think it should work now
